#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq - Sub7Seven
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: True
  tasks:
########################################## Install Script
  - name: Check DockerAssist Service
    stat:
      path: "/etc/systemd/system/assist.service"
    register: assistservice

  - name: Install Docker Reboot
    template:
      src: /pg/stage/ymls/templates/assist.sh
      dest: /pg/data/blitz/assist.sh
      force: yes

########################################## Install Service
  - name: Stop If DockerAssist Service Running
    systemd: state=stopped name=assistservice
    when: assistservice.stat.exists

  - name: Install DockerAssist Service
    template:
      src: /pg/stage/ymls/templates/assistservice.sh
      dest: /etc/systemd/system/assist.service
      force: yes

  - name: Daemon-Reload
    systemd: state=stopped name=assistservice daemon_reload=yes enabled=no

  - name: Start DockerAssist
    systemd: state=started name=assistservice enabled=yes
