#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install PGVPN
      template:
        src: pgvpn
        dest: /bin/pgvpn
        force: yes
        mode: 0775

    - name: Install Status UFSMonitor
      template:
        src: sufs
        dest: /bin/sufs
        force: yes
        mode: 0775

    - name: Nano UFSMonitor
      template:
        src: nufs
        dest: /bin/nufs
        force: yes
        mode: 0775

  ###### Install PGUpdate

    - name: PGUpdate
      template:
        src: pgupdate
        dest: /bin/pgupdate
        force: yes
        mode: 0775

  ###### Install PGBlitz

    - name: PlexGuide
      template:
        src: plexguide
        dest: /bin/plexguide
        force: yes
        mode: 0775
        owner: root
    - name: PG
      template:
        src: pg
        dest: /bin/pg
        force: yes
        mode: 0775
        owner: root
        
    - name: PGBlitz
      template:
        src: pgblitz
        dest: /bin/pgblitz
        force: yes
        mode: 0775
        owner: root

  ###### Server reboot

    - name: server reboot
      template:
        src: reboot
        dest: /bin/reboot
        force: yes
        mode: 0775

  ###### Check list of services

    - name: list systemd services
      template:
        src: slist
        dest: /bin/slist
        force: yes
        mode: 0775
        owner: root


  ###### Server update

    - name: update server
      template:
        src: update
        dest: /bin/update
        force: yes
        mode: 0775

  ###### Server upgrade

    - name: upgrade server
      template:
        src: upgrade
        dest: /bin/upgrade
        force: yes
        mode: 0775
        owner: root

  ###### Install app

    - name: install appname
      template:
        src: install
        dest: /bin/install
        force: yes
        mode: 0775
        owner: root

  ###### Autoremove installed app packages

    - name: autoremove unused packages after app install
      template:
        src: autoremove
        dest: /bin/autoremove
        force: yes
        mode: 0775
        owner: root

    - name: Prune docker containers appname
      template:
        src: prune
        dest: /bin/prune
        force: yes
        mode: 0775
        owner: root

    - name: Install PGFork
      template:
        src: pgfork
        dest: /bin/pgfork
        force: yes
        mode: 0775

    - name: Install Backup
      template:
        src: backup
        dest: /bin/backup
        force: yes
        mode: 0775
